### ISSUE TITLE
Create raspian packages

### ISSUE THREAD

**Issue by ckti** [cevap/ion#118]
Create raspian source and binary packages that can be downloaded and used/compiled for raspian.

**Comment by ckti** [comment]
ok, i now see why everyone was pulling their hair out raspian debuild tools are not playing nicely.  Will change tactics and try something else....

**Comment by ckti** [comment]
Seems to be building correctly using the regular source tree with autoreconf ./configure and make.  Got libdb 4.8 to build (to .deb) without any problems as well.

**Comment by ckti** [comment]
as i suspected, all works with regular autogen/autoreconf configure make.  the deb tools seem to be broken on the raspian i'm using.  will have to write a doc.

**Comment by ckti** [comment]
Was a broken debian/control file causing the issues have re-written and am rebuilding.

**Comment by ckti** [comment]
Should have the raspian stretch packages up tonight on https://ioncoin.000webhostapp.com .  Will also have the source for any who wpuld like to compile for different versions

**Comment by ckti** [comment]
raspian stretch is up at https://ioncoin.000webhostapp.com/raspian will update as need be

**Comment by ckti** [comment]
testing has shown a segfault in iond when opening wallet.dat after initial startup (this is under a vm raspian running on an odroid x4u).  Building natively on xenial arm.

**Comment by ckti** [comment]
possibly it's the compiler switches under raspian.  have taken out --disable-shared and compiling once more.

**Comment by ckti** [comment]
ramping up keypool now to find max size under arm

**Comment by ckti** [comment]
trying the full gamut of  --prefix=/usr -disable-shared --enable-cxx --with-pic didn't use these on fedora arm but did on x86_64.

**Comment by ckti** [comment]
also used these switches on ubuntu i386 & x86_64

**Comment by ckti** [comment]
still segfaulting

**Comment by ckti** [comment]
ion-qt segfaults as well

**Comment by ckti** [comment]
building db4.8 from http://sourcearchive.raspbian.org/main/d/db4.8/ will see what that produces

**Comment by mitchellcash** [comment]
If there are no issues we should update the guide to use this source

**Comment by ckti** [comment]
leaving arm for the time being.  will re-opne if new info becomes available.

**Comment by ckti** [comment]
Re-opening and setting to help wanted

**Comment by ckti** [comment]
trying yet another compilation method ....

**Comment by ckti** [comment]
it's definitely a wallet thing.   removing wallet.dat will get a proper startup.

**Comment by ckti** [comment]
trying a compile with --with-incompatible-bdb flag

**Comment by ckti** [comment]
trying with libdb5.3 ... will show if it's a compilation thing or a bdb thing

**Comment by ckti** [comment]
Works 100% on Fedora 26 arm

**Comment by ckti** [comment]
Trying fedora 23 once again

**Comment by ckti** [comment]
Trying a rebuild under raspian stretch armv7l db4.8 from raspian source archive

**Comment by ckti** [comment]
still segfaults.  Checking armbian xenial now

**Comment by ckti** [comment]
Segfaults under regular arm7l.  Will have to start looking at the OS to see if a sysctl tweak is needed that Fedora 26 arm does that everything else doesn't.

**Comment by ckti** [comment]
Here's the output of strace

stat64("/home/ckti/.ioncoin/wallet.dat", {st_mode=S_IFREG|0600, st_size=651264, ...}) = 0
open("/home/ckti/.ioncoin/wallet.dat", O_RDWR|O_CREAT|O_LARGEFILE, 0) = 18
---
then this error flies past numerous times
---
mlock(0x3e1b000, 4096)                  = -1 ENOMEM (Cannot allocate memory)

Will start into ulimit/sysctl debugging

**Comment by ckti** [comment]
full reinstall of fedora 26 on armv7l hardware. see if it still compiles and runs.

**Comment by ckti** [comment]
still compiles and runs under fedora 26 without any issues.

**Comment by ckti** [comment]
got coredump from fed 25 now building debug packages for fed arm 25 as I have a coredump and have found where the error comes in.
`Reading symbols from /usr/bin/iond...(no debugging symbols found)...done. [New LWP 14166] [Thread debugging using libthread_db enabled] Using host libthread_db library "/lib/libthread_db.so.1". Core was generated by `iond'. Program terminated with signal SIGSEGV, Segmentation fault. #0 0xb6a372a0 in std::local_Rb_tree_increment (x=0x5f657079)
    at ../../../../../libstdc++-v3/src/c++98/tree.cc:65
65              while (x->_M_left != 0)`

**Comment by ckti** [comment]
Here's where the problem lies afaict 
Fedora 25 (segfaulting)
`...}) = 0
open("/home/ckti/.ioncoin/wallet.dat", O_RDWR|O_CREAT|O_LARGEFILE, 000) = 15
fcntl64(15, F_GETFD)                    = 0
fcntl64(15, F_SETFD, FD_CLOEXEC)        = 0
fstat64(15, {st_mode=S_IFREG|0600, st_size=647168, ...}) = 0
gettimeofday({tv_sec=1512833736, tv_usec=708385}, NULL) = 0
pread64(15, "\0\0\0\0\1\0\0\0\3\0\0\0\0\0\0\0\0\0\0\0\232\0\210\3\2\3\364\17\234\6D\4"..., 4096, 12288) = 4096
pread64(15, "\0\0\0\0\1\0\0\0\177\0\0\0K\0\0\0\0\0\0\0F\0\304\4\1\5\320\17\300\17$\10"..., 4096, 520192) = 4096
pread64(15, "\0\0\0\0\1\0\0\0\4\0\0\0\0\0\0\0w\0\0\0\22\0\230\5\1\5\324\17\330\16\254\16"..., 4096, 16384) = 4096
mlock(0xbece4000, 4096)                 = 0
`
Fedora 26 (not segfaulting)

`gettimeofday({tv_sec=1512833873, tv_usec=978118}, NULL) = 0
gettimeofday({tv_sec=1512833873, tv_usec=978250}, NULL) = 0
close(7)                                = 0
close(6)                                = 0
open("/home/ckti/.ioncoin/database/log.0000000001", O_RDWR|O_LARGEFILE) = 6
fcntl64(6, F_GETFD)                     = 0
fcntl64(6, F_SETFD, FD_CLOEXEC)         = 0
read(6, "\0\0\0\0\34\0\0\0\231\34/\253\210\t\4\0\20\0\0\0\0\0\240\0\0\0\0\0", 28) = 28
`

**Comment by ckti** [comment]
Narrowed this down.  Fedora 26 reads wallet then opens database
`open("/home/ckti/.ioncoin/wallet.dat", O_RDWR|O_LARGEFILE) = 8
fcntl64(8, F_GETFD)                     = 0
fcntl64(8, F_SETFD, FD_CLOEXEC)         = 0
fstat64(8, {st_mode=S_IFREG|0600, st_size=651264, ...}) = 0
close(8)                                = 0
mmap2(NULL, 196608, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x
b23de000
munmap(0xb23de000, 196608)              = 0
gettimeofday({tv_sec=1512833873, tv_usec=978118}, NULL) = 0
gettimeofday({tv_sec=1512833873, tv_usec=978250}, NULL) = 0
close(7)                                = 0
close(6)                                = 0
open("/home/ckti/.ioncoin/database/log.0000000001", O_RDWR|O_LARGEFILE) = 6
fcntl64(6, F_GETFD)                     = 0
`

**Comment by ckti** [comment]
Fedora 25 calls a completely different function after reading wallet.dat
`open("/home/ckti/.ioncoin/wallet.dat", O_RDWR|O_CREAT|O_LARGEFILE, 000) = 15

fcntl64(15, F_GETFD)                    = 0

fcntl64(15, F_SETFD, FD_CLOEXEC)        = 0

fstat64(15, {st_mode=S_IFREG|0600, st_size=647168, ...}) = 0

gettimeofday({tv_sec=1512833736, tv_usec=708385}, NULL) = 0

pread64(15, "\0\0\0\0\1\0\0\0\3\0\0\0\0\0\0\0\0\0\0\0\232\0\210\3\2\3\364\17\234\6D\4"..., 4096, 12288) = 4096

pread64(15, "\0\0\0\0\1\0\0\0\177\0\0\0K\0\0\0\0\0\0\0F\0\304\4\1\5\320\17\300\17$\10"..., 4096, 520192) = 4096

pread64(15, "\0\0\0\0\1\0\0\0\4\0\0\0\0\0\0\0w\0\0\0\22\0\230\5\1\5\324\17\330\16\254\16"..., 4096, 16384) = 4096

mlock(0xbece4000, 4096)                 = 0

mlock(0x401c000, 4096)                  = 0

`

**Comment by ckti** [comment]
Raspian shows something different as well fstat is 13 

stat64("/home/pi/.ioncoin/wallet.dat", {st_mode=S_IFREG|0600, st_size=659456, ...}) = 0
open("/home/pi/.ioncoin/wallet.dat", O_RDWR|O_CREAT|O_LARGEFILE, 000) = 13
fcntl64(13, F_GETFD)                    = 0
fcntl64(13, F_SETFD, FD_CLOEXEC)        = 0
fstat64(13, {st_mode=S_IFREG|0600, st_size=659456, ...}) = 0
gettimeofday({tv_sec=1512926814, tv_usec=432420}, NULL) = 0
mlock(0xbedd2000, 4096)                 = 0

It goes to mlock as well
WIll keep digging

**Comment by ckti** [comment]
In initial setup on raspberry pi I find 
`write(4, "Performing wallet upgrade to 600"..., 35) = 35`

and it doesn't go into the mlock/unlock portion

the final statement of the run is

`mlock(0xbeb1c000, 4096)                 = 0
munlock(0xbeb1c000, 4096)               = 0
gettimeofday({tv_sec=1512992842, tv_usec=829644}, NULL) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x5f08860b} ---
+++ killed by SIGSEGV +++`

**Comment by ckti** [comment]
Fedora 25 gdb output
Core was generated by `iond'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xb6a372a0 in std::local_Rb_tree_increment (__x=0x5f657079)
    at ../../../../../libstdc++-v3/src/c++98/tree.cc:65
65              while (__x->_M_left != 0)

Raspi gdb output
Core was generated by `iond'.
Program terminated with signal SIGSEGV, Segmentation fault.
#-1 0xb6949a18 in ?? () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6

will now have a look at libstdc++ on fedora 26 and see where it differs from the others

**Comment by ckti** [comment]
Think I found it,
Fedora 26 libstdc++
Name        : libstdc++
Version     : 7.2.1
Release     : 2.fc26
Architecture: armv7hl

Fedora 25 libstdc++
Name        : libstdc++
Version     : 6.4.1
Release     : 1.fc25
Architecture: armv7hl

Rpi
Package: libstdc++6
Status: install ok installed
Priority: important
Section: libs
Installed-Size: 1706
Maintainer: Debian GCC Maintainers <debian-gcc@lists.debian.org>
Architecture: armhf
Multi-Arch: same
Source: gcc-6
Version: 6.3.0-18+rpi1
Replaces: libstdc++6-6-dbg (<< 4.9.0-3)
Provides: libstdc++6-armhf

WIll try a compile under gcc-7

**Comment by ckti** [comment]
Have gcc7 installed now under raspian.
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  gcc-7          7.2.0-16+rpi armhf        GNU C compiler

**Comment by ckti** [comment]
gcc-7 compiled iond no longer segfaults with wallet.  Will now start into building a package that runs natively on raspian stretch.  Will update the docs accordingly.

**Comment by ckti** [comment]
~90% sure i'll have a beta up today

**Comment by ckti** [comment]
Have a package now for raspberry pi stretch.  It's up at https://ioncoin.000webhostapp.com

**Comment by ckti** [comment]
creating armbian xenial package

**Comment by ckti** [comment]
Will consider this one closed now.
