### ISSUE TITLE
Test gitian build: Linux OS (v3.1.0-rc7.2)

### ISSUE THREAD

**Issue by cevap** [cevap/ion#125]
### PreRelease v3.1.00-rc7.2: 
[![PreRelease v3.1.00-rc7.2](https://img.shields.io/github/downloads/cevap/ion/v3.1.00-rc7.2/total.svg)](https://github.com/cevap/ion/releases/v3.1.00-rc7.2)

### Downloads binaries for Linux:
[![Download ion binaries for Linux AARCH64](https://img.shields.io/github/downloads/cevap/ion/v3.1.00-rc7.2/ion-3.1.00-aarch64-linux-gnu.tar.gz.svg)](https://github.com/cevap/ion/releases/download/v3.1.00-rc7.2/ion-3.1.00-aarch64-linux-gnu.tar.gz) [![Download ion binaries for Linux ARM](https://img.shields.io/github/downloads/cevap/ion/v3.1.00-rc7.2/ion-3.1.00-arm-linux-gnueabihf.tar.gz.svg)](https://github.com/cevap/ion/releases/download/v3.1.00-rc7.2/ion-3.1.00-arm-linux-gnueabihf.tar.gz) [![Download ion binaries for Linux i686](https://img.shields.io/github/downloads/cevap/ion/v3.1.00-rc7.2/ion-3.1.00-i686-pc-linux-gnu.tar.gz.svg)](https://github.com/cevap/ion/releases/download/v3.1.00-rc7.2/ion-3.1.00-i686-pc-linux-gnu.tar.gz) [![Download ion binaries for Linux x86_64](https://img.shields.io/github/downloads/cevap/ion/v3.1.00-rc7.2/ion-3.1.00-x86_64-linux-gnu.tar.gz.svg)](https://github.com/cevap/ion/releases/download/v3.1.00-rc7.2/ion-3.1.00-x86_64-linux-gnu.tar.gz)

#### Logs (Linux)
[build.log](https://github.com/cevap/ion/releases/download/v3.1.00-rc7.2/ion-3.1.00-rc7.2-linux-build.log), [install.log](https://github.com/cevap/ion/releases/download/v3.1.00-rc7.2/ion-3.1.00-rc7.2-linux-install.log)

#### Gitian signatures
- @gitianuser   [3.1.00-rc7.2-linux](https://github.com/gitianuser/gitian.sigs-ion/tree/master/3.1.00-rc7.2-linux)

**Comment by cevap** [comment]
## Test binaries on Ubuntu bionic (18.04.1 LTS) (x86_64-linux)
Distributor ID:	`Ubuntu`
Description:	`Ubuntu 18.04.1 LTS`
Release:	`18.04`
Codename:	`bionic`

- [x] - Test **x86_64-linux** QT binary
       - QT Wallet general user experience
         - QT launch and version
           ![grafik](https://user-images.githubusercontent.com/24996551/50371459-7f0b9700-05bb-11e9-894c-1279ce8cd601.png)
           ![grafik](https://user-images.githubusercontent.com/24996551/50371438-48358100-05bb-11e9-94aa-e741174b01ac.png)
![grafik](https://user-images.githubusercontent.com/24996551/50371480-e9243c00-05bb-11e9-890b-006b6ab7da3d.png)
- [x] Clean sync
- [x] Debug console
- [x] Windows and tools 
- [x] Keyboard and mouse

**Comment by ckti** [comment]
Building under pbuilder & launchpad with depends

**Comment by ckti** [comment]
runs under armhf
[x] trusty
[x] xenial
[x] bionic
[x] fedora 27
[x] fedora 28
[x] armbian
[x] raspberry pi (32 bit)

**Comment by ckti** [comment]
- first pbuilder results in, works with no keyboard bug

**Comment by ckti** [comment]
Pbuilder built binaries run with no keyboard bug
- [x] trusty i386
- [x] trusty amd64
- [x] xenial i386
- [x] xenial amd64
- [x] bionic i386
- [x] bionic amd64

**Comment by ckti** [comment]
Release build runs on:
- [x] trusty i386
- [x] trusty amd64
- [x] xenial i386
- [x] xenial amd64
- [x] bionic i386
- [x] bionic amd64
- [x] fedora 27 x86_64
- [x] fedora 28 x86_64

**Comment by FornaxA** [comment]
Tested on bionic and xenial - all fine here.
