### ISSUE TITLE
Proposal: rename ion-* builds to ioncoin-*

### ISSUE THREAD

**Issue by cevap** [cevap/ion#14]
There are several reasons for that.

1. Launchpad should be inline with snap builds, as _we can also build snaps over launchpad_, it works.
2. Some scripts would work better and are easier to deploy.
3. We use ioncoin already on snap
4. We want to have same naming on launchpad
5. Ion exists as a package and it is in higher version than our wallet, but having same naming causes issues for some users during the upgrade

Please discuss.

**Comment by FornaxA** [comment]
I'm all for this renaming, but what do we rename and what not? 
Just package names I assume? I don't see the need to rename iond to ioncoind based on the argumentation above - because the other ion package has different executable names.

**Comment by cevap** [comment]
[I don't see the need to rename iond to ioncoind based](url)
that was not suggested, it was suggested to that packages are named with ioncoin, not ion, binaries can stay like they are.

**Comment by ckti** [comment]
does this mean that i need to change the launchpad ion names on my side as well to ioncoin, ioncoin-qt and ioncoin-iond and the Fedora packages to ioncoin, ioncoin-qt, ioncoin-iond and ioncoin-doc? A bit more work on the fedora packages as they are built out of the same SRPM, but doable nonetheless....let me know

**Comment by cevap** [comment]
we will wait with this change until the move is done to ioncoincore and we will create  IIP about this change. With that I will close this issue, reopen it please when this topic gets to priority list.
