### ISSUE TITLE
Mac Qt Coin Control only shows max 10 addresses in tree mode

### ISSUE THREAD

**Issue by mdpfeiffer** [cevap/ion#17]
### Describe the issue

In Mac Qt Coin Control, only ten addresses are fully visible in tree mode. I cannot adjust the geometry of the screen to make the frame bigger. I cannot scroll down to see the 11th address. I cannot touch click the disclosure triangle because it is covered by the horizontal navigation bar at the very bottom of the frame.

### Can you reliably reproduce the issue?
Yes.
#### If so, please list the steps to reproduce below:
1. Click "Send" on the vertical menu bar.
2. Click "Open Coin Control"
3. Select Tree Mode
4. Attempt to scroll below 10th address
5. Attempt to click disclosure triangle for 11th address

### Expected behavior
When I try to scroll, I expect to be able to view and access all addresses in the wallet.
I expect to be able to click the disclosure triangle to view and manage each transaction in all addresses in the wallet.
I expect to be able to adjust the geometry of the frame if it is not large enough to accommodate all entries.

### Actual behavior
I cannot scroll down to see the 11th address. 
I cannot touch click the disclosure triangle because it is covered by the horizontal navigation bar at the very bottom of the frame.
I cannot adjust the geometry of the screen to make the frame bigger. 

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
![screen shot of coin control](https://user-images.githubusercontent.com/1129489/38163906-97fd7648-34c9-11e8-856f-41159e7701e6.jpg)

### What version of Ion Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

Ion Core version v3.0.4.0-78f3ad09-CEVAP (64-bit)
High Sierra build downloaded from https://github.com/cevap/ion/releases

### Machine specs:
- OS: 10.13.4 (17E199)
- CPU: 3.1 GHz Intel Core i7
- RAM: 16
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by cevap** [comment]
This seems to be only High Sierra related.

Can somebody with lower version confirm same bug as well to check on Sierra High?

On linux and windows I neither have nor can reproduce this issue, sample screenshot:
![image](https://user-images.githubusercontent.com/24996551/38169298-c9bf93b2-3566-11e8-9b27-b73e6281d012.png)

**Comment by mitchellcash** [comment]
I have corrected a Qt dependency issue related to the High Sierra build only and @mdpfeiffer has tested and confirmed this issue is now resolved.

Build uploaded to https://github.com/cevap/ion/releases/download/3.0.4/ion-3.0.4-osx-high-sierra-unsigned.dmg.
