### ISSUE TITLE
Discuss guidelines/policies ASAP

### ISSUE THREAD

**Issue by cevap** [cevap/ion#2]
### Guidelines
Guidelines and policies have to be discussed and set ASAP.

**Comment by aspaas** [comment]
ION has been forked once, will be forked again soon, and it's likely to fork again in the future (like most coins).
A fork is accompanied by a change in code, and this change depends on block height (e.g. nHeight) and block time (e.g. nTime). After such a marked point, some algo's are typically changed, such as the difficulty retargeting algo.
How do we reference these marked points in the source code? For now, I've adopted what I've seen in other coins such as Orbitcoin, Stratis and Peercoin, and slightly tweaked it:
- nFork1Height refers to the block nr that is the last block using the old protocol
- Fork1Height() is a function of Params(), which is globally accessible. This sets ION apart from coins that make nFork1Height a globally accessible variable (inline static). The advantage is that the height has become dependent on if the client is running mainnet or testnet (as opposed to using e.g. nFork1TestnetHeight, or to testing for Testnet()).

Should more meaningful names be introduced, such as nForkCoinbleedFixHeight?
Are there other alternatives?
(Having numbers in variables can be confusing and can invite errors).

**Comment by cevap** [comment]
I do believe that nForkCoinbleedFixHeight would fit much better, as it even explains in name what it is.

I clearly would dislike to mix up letters and numbers in variables unless it has to be done.

Regarding naming conventions:

- bitcoin itself is the source for all coins which are sources of ion. Naming convention should be targeted to the actual core this coin wants to come closer, in current case it is bitcoin
- bitcoin has contribution, release, ... guidelines and policies which showed to be efficient like the time has proven.
- Bitcoin is very liberal regarding naming conventions and every developer has its own style/naming conventions. I would also dislike something like a prefix `gv_`, `gc_`, `lv_`, `lc_`, .... (g- global, l- local).

All in all, I would stay fully liberal, but would mark some directions which we could take from other concepts, here the main goal would be to apply something that improves code readability which makes it easier for everybody. 

But here some points for orientation:
- Should clearly state by name what it is
- Should be debranded (like darksend as example, that is another product, of another crypto project)
- Letters and numbers should not be mixed up in naming/labels

I think technical documentation is good starting point for fast overview of naming convention question, we simply would need to set a project with a progress and go from A-Z to look.

Beside that, all descriptions and explanations should exist (and we miss currently many).

I think we can do that all on the fly, important is to be sure to choose naming wisely, as if you later need to replace a bunch of files, you will be very gratefull if everything works correctly withot messing up something else.

But again, that's how most of those who contribute should work, I will not push anything, as contributors should decide based on their own imagination/experience/skills.

I would not mind to hear some other people just expressing what they believe would be best path. So far, I'll stick to bitcoin.
