### ISSUE TITLE
Publish ion donation addresses for every public key (ℹ️ some contributors could have same name)

### ISSUE THREAD

**Issue by cevap** [cevap/ion#27]
Steps to be done
---------------------

 1 Add ion donation addresses for each supplied public key
 1 Add QR code for each ion address

ℹ️ - Currently everything is added to [doc/donation.md](../tree/master/doc/donation.md))

**Comment by mitchellcash** [comment]
My ion address iTSzxxH4ShZBAdfBYiTY6PeMYqkmA5d5aV
