### ISSUE TITLE
Publish bitcoin donation addresses for every public key (ℹ️ some contributors could have same name)

### ISSUE THREAD

**Issue by cevap** [cevap/ion#29]
This is optional, as we have at least 2 addresses, this issue is to be seen as done.

Fixed with following commit: https://github.com/cevap/ion/commit/03182ba446f55224b51b4ce23902ecf08f64f07a

Follwing addresses have been added
---------------------------------------------

🗺 [CEVAP (dev@i2pmail.org)](https://github.com/cevap/)
===========================

 - **Btc**: [3DHhT6c2BN86Tx6D2w615UUSFvUwT41jY7](bitcoin:3DHhT6c2BN86Tx6D2w615UUSFvUwT41jY7)

     ![Donate BTC to 🐼CEVAP🐼](https://raw.githubusercontent.com/cevap/ion/master/doc/donation/donation-cevap-btc-address.png)

🗺 [🔩ASPA🔩](https://github.com/aspaas/)
----------

 - **Btc**: [1DKj3yeJrMShP8MdnKpTTG8TKb7ymaFN1p](bitcoin:1DKj3yeJrMShP8MdnKpTTG8TKb7ymaFN1p)

     ![Donate BTC to 🔩ASPA🔩](https://raw.githubusercontent.com/cevap/ion/master/doc/donation/donation-aspa-btc-address.png)

**Comment by cevap** [comment]
Addresses updated. This is optional and will be closed now.

**Comment by mitchellcash** [comment]
My bitcoin address 14barGgijZmvXAKwMDrQLjChfKuwtnfCfW
