### ISSUE TITLE
ION QT v2.1.6.0-61402 Masternode Issues

### ISSUE THREAD

**Issue by CarlShawn** [cevap/ion#30]
### Describe the issue
Encrypted wallet. Followed instructions in Wiki for setting up Masternode. Masternode would start, then stop after a while. Would try to restart but it said invalid private key. It would then lock the wallet. Tor suggested exporting keys and trying again clean, without encrypting wallet. Block sync was very slow from scratch, required constant close and reopens when it would hang. After sync, checkwallet, repair wallet, then close and copy over of Masternode and Ioncoin.conf, start wallet, start masternode, it started but after about an hour it said it was not in the Masternode list. Start node up again and it runs. Will see how long. No stakes.

### Can you reliably reproduce the issue?
Yes.

#### If so, please list the steps to reproduce below:
1. Install wallet and sync from scratch.
2. Import priv keys.
3. Go through Wiki Masternode steps.
4. Start Masternode and wait for it to stop running.
5. I have not encrypted the wallet again, but doing so will create a loop of sorts in trying to unlock the wallet for staking. It will unlock, but show an Circle with an X that it is not staking. Unlock wallet completely and it looks like it is staking. Once starting the masternode it gives the private key not valid and locks wallet. The priv key works fine when wallet not encrypted.
6. Also, edit button does not do anything on masternode list.

### Expected behaviour
Wallet should sync blockchain from scratch without restarts. Masternode should run with encrypted wallet.

### Actual behaviour
Will not stay running with encrypted wallet and end up giving a private key invalid message after restart.

### What version of ion-core are you using?
ION QT v2.1.6.0-61402

### Machine specs:
- OS: Windows 10 Pro 64bit, Version 1607 (OS Build 14393.1358)
- CPU: AMD FX-8350
- RAM: 32GB
- Disk size: 4TB, WD4001FAEX-00MJRA0
- Disk Type (HD/SDD): HD

### Any extra information that might be useful in the debugging process.
I can provide a debug.log file. Is there anything sensitive in it that I should redact?

Should the masternode.conf file be formatted like the ioncoin.conf? Looks like the masternode file is space delimited. Should reduce errors with variable=data syntax.

**Comment by CarlShawn** [comment]
Received "Not in masternode list" and masternode stopped. Ran for about thirty minutes. Checked debug.log file with no mention of an error other than this:
2017-07-04 19:00:52 ERROR: ConnectInputs() : 78e837da47f528375cc87fd38ba27071a90a170e99ebd7172fce61add430e518 prev tx already used at (nFile=1, nBlockPos=136100221, nTxPos=136100370)
2017-07-04 19:00:52 ERROR: AcceptableInputs : ConnectInputs failed 78e837da47f528375cc87fd38ba27071a90a170e99ebd7172fce61add430e518
2017-07-04 19:03:49 dseep - Asking source node for missing entry CTxIn(COutPoint(e5158bfab7, 0), scriptSig=)
2017-07-04 19:05:44 dsee - Got updated entry for 45.77.37.112:12706

**Comment by CarlShawn** [comment]
Restarted wallet and now the invalid private key message.
![ion error mn](https://user-images.githubusercontent.com/4350739/27841034-a13fee14-60c3-11e7-92d3-e084646eac98.jpg)

**Comment by CarlShawn** [comment]
Renamed masternode.conf. Created it again in GUI and it will start with the same data.
![ion error mn 2](https://user-images.githubusercontent.com/4350739/27841117-4357462a-60c4-11e7-8b1c-1d909d77e4b4.jpg)

**Comment by CarlShawn** [comment]
Looks like it might be a space parsing issue on the Alias. Changing to one word.

**Comment by cevap** [comment]
thanks for report, we will look at it

**Comment by cevap** [comment]
WIth this https://github.com/cevap/ion/pull/36 (thx @aspa) commit it QT is being compiled.

##### Here is how I currently compiled
```
git clone https://github.com/cevap/ion.git
cd ion/depends
make
cd ..
./autogen.sh
./configure ./configure --enable-glibc-back-compat --prefix=`pwd`/depends/x86_64-pc-linux-gnu LDFLAGS="-static-libstdc++"
make
```
