### ISSUE TITLE
Automatic wallet update

### ISSUE THREAD

**Issue by leojavi2** [cevap/ion#31]
Hello ionomy team, I've seen in Crown's wallet (which is very similar to Ion's), that in the help tab, has an option to update the wallet, it would be very good if we can incorporate it into the ionomy wallet

**Comment by mitchellcash** [comment]
@leojavi2 while I like the idea of being able to auto-update clients, it's not without it's problems.

Crown relies on a centralised service to monitor the update mechanism (being GitHub). As some of the lead Bitcoin devs point out:

> The result of someone hijacking github, controlling people's connections, or holding one of the developers with access at gunpoint could be very problematic. Of course, that problem exists now too, but without mechanism to explicitly push out new releases, such an attempt would be delayed significantly.

> Because you push a malicious version, and then update the autoupdate notice and then very rapidly you have stolen the wallets of tens of thousands of people before anyone clueful has had a chance to notice.

There would be ways around this, but they aren't without a reasonable amount of work involved (hence why we don't see Dash, LTC, BTC etc. implement this approach).

Some potentially dated thoughts on how it could work:

> The plan for auto-updating involved requiring several independent signatures from developers (and perhaps others), including the ability to sign a message against a particular version. This would make such an attack much harder, but also complicates the implementation of an auto-update scheme.

**Comment by cevap** [comment]
@leojavi2 thanks for suggestion.

We have much better way of deployment. We offer several ways of auto update. Please look 
- Launchpad : https://launchpad.net/~ionomy/+archive/ubuntu/ioncoin
- Snap: https://build.snapcraft.io/user/cevap/ion
  (_this is always latest master_) (_successfully built only_)

You can also always see the status of master branch:
![grafik](https://user-images.githubusercontent.com/24996551/38482556-2160a9b6-3bd0-11e8-81a2-dde5837bf316.png)

I will close this one, but feel free to answer if you would still like to have some autoupdate mechanism which we currently do not offer.
