### ISSUE TITLE
Check build process

### ISSUE THREAD

**Issue by cevap** [cevap/ion#4]
### Describe the issue
iond is over 100mb

#### If so, please list the steps to reproduce below:
1. ./autogen.sh
2. ./configure
3. make

### Expected behaviour
iond should have similar size like QT version.

### Actual behaviour
It looks like if its compiled as debug version and not as release

### What version of ion-core are you using?
2.1.5.3

### Machine specs:
- OS: Linux
- CPU: i7
- RAM: 64Gb
- Disk size: 1Tb
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by mitchellcash** [comment]
@cevap which OS? And are you building cevap/ion:master?

Mine are much smaller than this on Mac for v2.1.6.

**Comment by cevap** [comment]
My ion-qt is 9mb and iond 5mb (you can run `strip Binary` to get it in smaller size.

The problem here, no ion-qt is being beuilt with `autogen.sh;./configure;make`. Currently QT version works with only `qmake && make` or building with QT creator.

**Comment by cevap** [comment]
You can compile static version, as example like that:
`./configure --enable-glibc-back-compat --prefix=`pwd`/depends/x86_64-pc-linux-gnu LDFLAGS="-static-libstdc++";make`

Then `strip iond` and your file size will be much smaller.

**Comment by cevap** [comment]
fixed and closed (https://github.com/cevap/ion/commit/9710d2b6450ca42a74bb1c0f9b14bc6db587e9bb)

**Comment by cevap** [comment]
ion-qt broken with this change: https://github.com/cevap/ion/commit/71c2226b8583465bc8f5d847be511c84705ad558

Either it breaks because of version change or release=true breaks it, this has to be rechecked.
