### ISSUE TITLE
🗺️👯👯 Language Translations - *.md files

### ISSUE THREAD

**Issue by cevap** [cevap/ion#40]
We should translate these files as first, as they will provide a community of different geo locations to learn and contribute:

[Project overview](../projects/10)

```
./INSTALL.md
./depends/description.md
./depends/packages.md
./depends/README.md
./share/rpcuser/README.md
./share/certs/PrivateKeyNotes.md
./CONTRIBUTING.md
./doc/release-notes.md
./doc/build-osx.md
./doc/build-openbsd.md
./doc/gitian-building.md
./doc/donation.md
./doc/UbuntuPPA.md
./doc/release-process.md
./doc/init.md
./doc/reduce-traffic.md
./doc/travis-ci.md
./doc/files.md
./doc/assets-attribution.md
./doc/dnsseed-policy.md
./doc/release-notes/release-notes-2.1.6.0.md
./doc/release-notes/release-notes-2.1.6.1.md
./doc/README_osx.md
./doc/shared-libraries.md
./doc/bips.md
./doc/benchmarking.md
./doc/developer-notes.md
./doc/release-notes-2.1.6.2.md
./doc/build-windows.md
./doc/README.md
./doc/translation_process.md
./doc/fuzzing.md
./doc/REST-interface.md
./doc/zmq.md
./doc/publickeys.md
./doc/tor.md
./doc/build-unix.md
./doc/translation_strings_policy.md
./contrib/static-build-scripts/README.md
./contrib/testgen/README.md
./contrib/qos/README.md
./contrib/ssh-keys/README.md
./contrib/init/README.md
./contrib/debian/examples/README.md
./contrib/debian/README.md
./contrib/verifybinaries/README.md
./contrib/seeds/README.md
./contrib/devtools/README.md
./contrib/gitian-keys/README.md
./contrib/rpm/README.md
./contrib/verify-commits/README.md
./contrib/linearize/README.md
./contrib/README.md
./contrib/gitian-descriptors/README.md
./contrib/macdeploy/README.md
./README.md
./test/README.md
./test/functional/README.md
./src/leveldb/WINDOWS.md
./src/leveldb/CONTRIBUTING.md
./src/leveldb/README.md
./src/secp256k1/README.md
./src/qt/plugins/mrichtexteditor/README.md
./.github/ISSUE_TEMPLATE.md
```

**Comment by cevap** [comment]
[Ionomy's slack community](https://ionomy.slack.com/) seems not to be informed or nobody wants/can help with languages.

Should I promote this as bounty in public or should we wait until [ionomy's slack community](https://ionomy.slack.com/) finds out about existance of [🐼 CEVAP 🐼](https://github.com/cevap/).

**Comment by aspaas** [comment]
I will setup transifex this week, and then we can give it a week until we promote it differently.

**Comment by cevap** [comment]
thanks, but no need to setup transifex, we have it already.

Ion core on transifex: https://www.transifex.com/cevap-1/ion-1/dashboard/

We still need native speakers to verify translations. I know that we can not cover all languages, but at least prioritized as then we could also provide communication in same language.

**Comment by cevap** [comment]
seems like somebody else of you registered cevap without to notify me/here.

**Comment by cevap** [comment]
@aspaas that was wrong (from my point). As it should have been registered with github's account (CEVAP) not with your (aspa)

**Comment by cevap** [comment]
The one I've setup has already languages setup: https://www.transifex.com/cevap-1/public/

This kinda is not optimal @aspaas . I did now the same work on wrong (not optimal account). I suggest to close now both accounts, that is now a problem and is responsible for time loss. That should not happen. For that reason I create projects.

With that, topic closed, I will not wait for slack community and will abandon languages as part of the project due to the lack of interest. Feel free to open it if anybody some miracle happens.
