### ISSUE TITLE
Dubious dsee logging entry

### ISSUE THREAD

**Issue by aspaas** [cevap/ion#5]
### Describe the issue

During testing the additional time warp checks, binary logging entries appeared in debug.log:

```2017-06-21 18:50:09 received: dseep (116 bytes)
2017-06-21 18:50:09 dseep - Couldn't find masternode entry CTxIn(COutPoint(f3b9d6d0d6, 1), scriptSig=)
2017-06-21 18:50:09 dseep - Asking source node for missing entry CTxIn(COutPoint(f3b9d6d0d6, 1), scriptSig=)
2017-06-21 18:50:09 sending: dseg (41 bytes)
2017-06-21 18:50:09 received: dsee (258 bytes)
2017-06-21 18:50:09 dsee -
á.ô:>.À_ì.nóA.J...ɀ.+ڗÃ.ÖÐֹó.....ÿÿÿÿ..........ÿÿ3.5Z¿¯A..E..eÁv>.L©.y¶<.¥FGî°æ`«Îð`¾]Uöy.¾ÐTÔ?²..ũ¸.Ææ×#ó¼).Gq.ËeX.ë.jXBh*Y....!.»ú..4*.°¯.cÌÓïl..V¯µ.ãâö #®míPA.e.s¼W.pߛ£8.£...6
.Ë!½£2Á㖣ÂW.. ¹2M^ª ...[.åZbÎøÆYéĝü.O..N.Ojì>...`...á¿JY....uu.......
2017-06-21 18:50:09 dsee - Got NEW masternode entry 51.15.53.90:49071
2017-06-21 18:50:09 dsee - Accepted masternode entry 318 96
2017-06-21 18:50:09 CMasternodeMan: Adding new masternode 51.15.53.90:49071 - 37 now
2017-06-21 18:50:10 received: dseep (116 bytes)
2017-06-21 18:50:10 dseep - Couldn't find masternode entry CTxIn(COutPoint(8701aec1dc, 0), scriptSig=)
2017-06-21 18:50:10 dseep - Asking source node for missing entry CTxIn(COutPoint(8701aec1dc, 0), scriptSig=)
2017-06-21 18:50:10 sending: dseg (41 bytes)
2017-06-21 18:50:11 received: dsee (258 bytes)
2017-06-21 18:50:11 dsee - c.*V...3+.UËËu¤*Ø{.v#âÈ/܆=ÜÁ®.......ÿÿÿÿ..........ÿÿ-L3.09A..Ë=?..
ÎN'$ø2É#ѝ.+
ÆÀRFg럱2.Jb.yOI.ñè.ä.z..)Vw*<.}àϪ$ª.n 9·.öHY....!.(º7û;noV .¬Õ..%#.ÓfM°÷6.KâIR:.. A.V.5)í:_ûS[k.b.ù©¼ªSx3ÏgÐ.0
§.ä.ô.Նy.úº gØC7$..â..ú~]{=.Ò3.(²ZV>... ...â¿JY....uu.......
2017-06-21 18:50:11 dsee - Got NEW masternode entry 45.76.51.23:12345
2017-06-21 18:50:11 dsee - Accepted masternode entry 318 265
2017-06-21 18:50:11 CMasternodeMan: Adding new masternode 45.76.51.23:12345 - 38 now
```
Bin2hex for the binary parts gives:

```c3a12ec3b43a3e2ec3805fc3ac2e6ec3b3412e4a2e2e2ec9802e2bda97c3832ec396c390d6b9c3b32e2e2e2e2ec3bfc3bfc3bfc3bf2e2e2e2e2e2e2e2e2e2ec3bfc3bf332e355ac2bfc2af412e2e452e2e65c381763e2e4cc2a92e79c2b63c2ec2a54647c3aec2b0c3a660c2abc38ec3b060c2be5d55c3b6792ec2bec39054c3943fc2b22e2ec5a9c2b82ec386c3a6c39723c3b3c2bc292e47712ec38b65582ec3ab2e6a5842682a592e2e2e2e212ec2bbc3ba2e2e342a2ec2b0c2af2e63c38cc393c3af6c2e2e56c2afc2b52ec3a3c3a2c3b62023c2ae6dc3ad50412e652e73c2bc572e70df9bc2a3382ec2a32e2e2e360a2ec38b21c2bdc2a332c381e396a3c382572e2e20c2b9324d5ec2aa202e2e2e5b2ec3a55a62c38ec3b8c38659c3a9c49dc3bc2e4f2e2e4e2e4f6ac3ac3e2e2e2e602e2e2ec3a1c2bf4a592e2e2e2e75752e2e2e2e2e2e2e```

and:

```632e2a562e2e2e332b2e55c38bc38b75c2a42ac3987b2e7623c3a2c3882fdc863dc39cc381c2ae2e2e2e2e2e2e2ec3bfc3bfc3bfc3bf2e2e2e2e2e2e2e2e2e2ec3bfc3bf2d4c332e3039412e2ec38b3d3f2e2e0ac38e4e2724c3b832c38923d19d2e2b0ac386c380524667eb9fb1322e4a622e794f492ec3b1c3a82ec3a42e7a2e2e2956772a3c2e7dc3a0cfaa24c2aa2e6e2039c2b72ec3b648592e2e2e2e212e28c2ba37c3bb3b6e6f56202ec2acc3952e2e25232ec393664dc2b0c3b7362e4bc3a249523a2e2e20412e562e3529c3ad3a5fc3bb535b6b2e622ec3b9c2a9c2bcc2aa537833c38f67c3902e300ac2a72ec3a42ec3b42ed586792ec3bac2ba2067c3984337242e2ec3a22e2ec3ba7e5d7b3d2ec392332e28c2b25a563e2e2e2e202e2e2ec3a2c2bf4a592e2e2e2e75752e2e2e2e2e2e2e```

Comparable messages can be produced by adding the following logging function after deserialization of vRecv in CMasternodeMan::ProcessMessage():

```        vRecv >> vin >> addr >> vchSig >> sigTime >> pubkey >> pubkey2 >> count >> current >> lastUpdated >> protocolVersion >> donationAddress >> donationPercentage;

        LogPrint("masternode", "masternodeman.cpp: dsee - vin=(%s)", vin.ToString());
```
Which produces:

```
C[á.ð>¢..>ï%û³ðA²Üæ.}t³.²{B.þ¸AE.....ÿÿÿÿ..........ÿÿ-?.^1.A 6õÝß%³@.VòtR÷µÃ}þ.ðvÅ[É,.¡..3ß)äaÙ.õÎæ..K]½Ìú§.Jåó.ëÚ÷õ.ø."æÿ.c[wFY....
!..1Ýټͦ.¶2.% b...Àº ub.r..[à¬u¶øA. ('îĨºK.ßoªc^ïg.i§:.=9.ô@ÃÌ...bZæ.¸..-ùó<§.T¬§.6_
èÜV³.¥[Ò9Ýè£YB...Õ...   äJY....uu.......
```

Or:
```435bc3a12ec3b03ec2a22e2e3ec3af25c3bbc2b3c3b041c2b2c39cc3a62e7d74c2b32ec2b27b422ec3bec2b841452e2e2e2e2ec3bfc3bfc3bfc3bf2e2e2e2e2e2e2e2e2e2ec3bfc3bf2d3f2e5e312e412036c3b5c39dc39f25c2b3402e56c3b27452c3b7c2b5c3837dc3be2ec3b076c3855bc3892c2ec2a12e2e33c39f29c3a461c3992ec3b5c38ec3a62e2e4b5dc2bdc38cc3bac2a72e4ac3a5c3b32ec3abc39ac3b7c3b52ec3b82e22c3a6c3bf2e635b7746592e2e2e2e0a212e2e31c39dd9bccda62ec2b6322e2520622e2e2ec380c2bac2a075622e722e2e5bc3a0c2ac75c2b6c3b8412ec2a02827c3aec4a8c2ba4b2ec39f6fc2aa635ec3af672e69c2a73a2e3d392ec3b440c383c38c2e2e2e625ac3a62ec2b82e2e2dc3b9c3b33cc2a72e54c2acc2a72e365f0ac3a8c39c56c2b32ec2a55bc39239c39dc3a8c2a359422e2e2ec3952e2e2e202020c3a44a592e2e2e2e75752e2e2e2e2e2e2e```

### Can you reliably reproduce the issue?

Not yet.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
It is not clear what the intended logging output should be. The LogPrint() function does not add a reference to the logging point in the code.

### Actual behaviour
Tell us what happens instead

### What version of ion-core are you using?
https://github.com/cevap/ion/commit/6cef92a0bec433abd49f4b4adcb7c3ee4b11fdd0

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by cevap** [comment]
did anybody else report similar or are there any known tickets similar to this?

**Comment by cevap** [comment]
There is no further information about this or that something is wrong, I will close this ticket now.

Feel free to reopen if further information is available.
