### ISSUE TITLE
Create Virtual Gitian environments for creation of binary packages

### ISSUE THREAD

**Issue by ckti** [cevap/ion#51]
Complete gitian-based images need to be created for compilation, installation and testing of ion* binaries under Ubuntu
- OS: Ubuntu Precise, Trusty, Vivid, Xenial, Yakkety, Zesty
- CPU: i386, x86_64

**Comment by ckti** [comment]
Finally got the method correct create qcow2 images for precise --> xenial
Create lxc images for yakkety & zesty
convert qcow2 --> vdi with qemu-img
convert lxc --> vdi with qcow 2
create blank 10GB disk image in VB
cpio -p from lxc --> partition 1 of blank disk
install kernel & grub to blank disk
boot under VB --> install dependencies --> cross fingers ;) --> compile ion
Once all VMs can compile full ion-qt/iond will start modifying my scripts to create the launchpad debs.

**Comment by cevap** [comment]
I created a project for this task: https://github.com/cevap/ion/projects/13 and linked it to the card id.

ℹ️ - _all steps will be created as cards and then converted to issues if further communication/changes are required_

**Comment by ckti** [comment]
Brilliant :)

**Comment by ckti** [comment]
OK, now getting to the make --prefix=`pwd`/depends/<LINUX_VER> for precise, the compiler has to be updated to 4.8 before it can build the depends...and I had to copy over a Makefile from cevap ion/depends to get it to compile :( once I have a stable src package i will test it in my ppa https://launchpad.net/~ckti/+archive/ubuntu/test-ioncoin and make sure it is working once I have a good source.

**Comment by ckti** [comment]
Have eight vdi images for building now.  Still have to configure some of them.  Writing build scripts to automate the processes.  May have to go back through and increase the hard drive sizes...10GB with an 8/2 split may not be enough room to build.

**Comment by ckti** [comment]
Have the gitian -> vdi process completed for precise -> zesty amd64 & i386

**Comment by cevap** [comment]
If all work except precise, lets release it.

**Comment by ckti** [comment]
will document and release....

**Comment by ckti** [comment]
Have now started in on the gitian-build documentation in earnest.  Not a complete rewrite...png images in need of updating are being updated..

**Comment by ckti** [comment]
All done for this one....can someone double check and if all ok merge it?

**Comment by ckti** [comment]
All done for this one....can someone double check and if all ok merge it?
