### ISSUE TITLE
The gitian guest cannot connect to the internet.

### ISSUE THREAD

**Issue by aspaas** [cevap/ion#54]

**Comment by aspaas** [comment]
This appears to be caused by the bridge network settings as described in (the gitian build docs)[doc/gitian-building.md].
The host runs on 10.0.2.0/24, so to bridge to that network, the guest needs to be on a different subnet. The docs tell it to go on the 10.0.2.0/24 network, what won't work.
To keep the differentiation with the bitcoin gitian build machines (10.0.3.0/24), I'll move them to the 10.0.4.0/24 network.

**Comment by aspaas** [comment]
Correction, lxc defaults assume 10.0.3.0/24.

Moreover, it seems debian 9 simplified the network bridging with (SimpleBridge)[https://wiki.debian.org/LXC/SimpleBridge]

Need to adapt, because bridging doesn't work in debian 9.

**Comment by cevap** [comment]
@aspaas can this be closed as we have updated gitian build process or is it related to latest one too?

Please reopen if so.
