### ISSUE TITLE
nsis dependencies aren't checked properly in autoconf.

### ISSUE THREAD

**Issue by aspaas** [cevap/ion#57]
The windows qt installer needs a makensis that can handle 'Unicode=true' (which is provided in the depends folder)

**Comment by cevap** [comment]
@aspaas how is the progress on this topic? Can we close this issue as we are not using some emojis now?

You can reopen it whenever you continue on NSIS/MSI.

**Comment by aspaas** [comment]
@cevap We can close it for now; nsis 3 is added to the Depends system, and it is compiled there, but it's not a requirement indeed, so it doesn't have to be added to the autoconf checks.
