### ISSUE TITLE
Create .deb packages for Supported Ubuntu versions amd64 & i386

### ISSUE THREAD

**Issue by ckti** [cevap/ion#60]
https://github.com/ckti/ion
ignore precise for time being concentrate on Ubuntu Upstream Versions Vivid -> Artful (due later this year)

**Comment by ckti** [comment]
Find step in process that is hanging the build process.  
--- think i've finally found it.....doing an autoreconf --> install; configure THEN trying to do the bzr builddeb rather than download, tar -czf,  bzr builddeb.  I'm watching a compile on my VDI console now :)

**Comment by ckti** [comment]
bzr builddeb -- -us -uc 
.
.
.
g++ -fstack-protector-all --param ssp-buffer-size=1 -Wl,-Bsymbolic-functions -Wl,-z,relro -o ion-qt build/txdb-leveldb.o build/ion.o build/iongui.o build/proofs.o build/uint256.o build/amount.o build/transactiontablemodel.o build/addresstablemodel.o build/bantablemodel.o build/optionsdialog.o build/sendcoinsdialog.o build/coincontroldialog.o build/coincontroltreewidget.o build/addressbookpage.o build/signverifymessagedialog.o build/aboutdialog.o build/editaddressdialog.o build/ionaddressvalidator.o build/alert.o build/allocators.o build/base58.o build/chainparams.o build/version.o build/sync.o build/txmempool.o build/util.o build/hash.o build/netbase.o build/ecwrapper.o build/key.o build/pubkey.o build/script.o build/core.o build/main.o build/miner.o build/init.o build/net.o build/checkpoints.o build/addrman.o build/db.o build/walletdb.o build/clientmodel.o build/guiutil.o build/transactionrecord.o build/optionsmodel.o build/monitoreddatamapper.o build/peertablemodel.o build/trafficgraphwidget.o build/transactiondesc.o build/transactiondescdialog.o build/ionstrings.o build/ionamountfield.o build/wallet.o build/keystore.o build/transactionfilterproxy.o build/transactionview.o build/walletmodel.o build/walletmodeltransaction.o build/rpcclient.o build/rpcprotocol.o build/rpcserver.o build/rpcdump.o build/rpcmisc.o build/rpcnet.o build/rpcmining.o build/rpcwallet.o build/rpcblockchain.o build/rpcrawtransaction.o build/overviewpage.o build/csvmodelwriter.o build/crypter.o build/sendcoinsentry.o build/qvalidatedlineedit.o build/ionunits.o build/qvaluecombobox.o build/askpassphrasedialog.o build/protocol.o build/notificator.o build/paymentserver.o build/rpcconsole.o build/noui.o build/stake.o build/cleanse.o build/stealth.o build/flowlayout.o build/stashedsendconfig.o build/masternode.o build/stashedsend.o build/stashedsend-relay.o build/rpcstashedsend.o build/instantx.o build/activemasternode.o build/masternodeman.o build/masternode-payments.o build/spork.o build/masternodeconfig.o build/hmac_sha256.o build/hmac_sha512.o build/ripemd160.o build/sha1.o build/sha256.o build/sha512.o build/masternodemanager.o build/addeditatomnode.o build/atomnodeconfigdialog.o build/qcustomplot.o build/qvalidatedtextedit.o build/multisigaddressentry.o build/multisiginputentry.o build/multisigdialog.o build/qrc_ion.o build/moc_iongui.o build/moc_transactiontablemodel.o build/moc_addresstablemodel.o build/moc_bantablemodel.o build/moc_optionsdialog.o build/moc_coincontroldialog.o build/moc_coincontroltreewidget.o build/moc_sendcoinsdialog.o build/moc_addressbookpage.o build/moc_signverifymessagedialog.o build/moc_aboutdialog.o build/moc_editaddressdialog.o build/moc_ionaddressvalidator.o build/moc_clientmodel.o build/moc_guiutil.o build/moc_optionsmodel.o build/moc_monitoreddatamapper.o build/moc_peertablemodel.o build/moc_trafficgraphwidget.o build/moc_transactiondesc.o build/moc_transactiondescdialog.o build/moc_ionamountfield.o build/moc_transactionfilterproxy.o build/moc_transactionview.o build/moc_walletmodel.o build/moc_overviewpage.o build/moc_csvmodelwriter.o build/moc_sendcoinsentry.o build/moc_qvalidatedlineedit.o build/moc_ionunits.o build/moc_qvaluecombobox.o build/moc_askpassphrasedialog.o build/moc_notificator.o build/moc_paymentserver.o build/moc_rpcconsole.o build/moc_stashedsendconfig.o build/moc_masternodemanager.o build/moc_addeditatomnode.o build/moc_atomnodeconfigdialog.o build/moc_qcustomplot.o build/moc_qvalidatedtextedit.o build/moc_multisigaddressentry.o build/moc_multisiginputentry.o build/moc_multisigdialog.o   /home/ubuntu/config.systemd/build-area/ioncoin-2.1.6.1/src/leveldb/libleveldb.a /home/ubuntu/config.systemd/build-area/ioncoin-2.1.6.1/src/leveldb/libmemenv.a /home/ubuntu/config.systemd/build-area/ioncoin-2.1.6.1/src/secp256k1/src/libsecp256k1_la-secp256k1.o -lminiupnpc -lssl -lcrypto -ldb_cxx -lgmp -lboost_system -lboost_filesystem -lboost_program_options -lboost_thread -lrt -ldl -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Network -lQt5DBus -lQt5Core -lpthread -lGL 
build/ion.o: In function `main':
/home/ubuntu/config.systemd/build-area/ioncoin-2.1.6.1/src/qt/ion.cpp:142: undefined reference to `qInitResources_ion_locale()'
collect2: error: ld returned 1 exit status
Makefile:676: recipe for target 'ion-qt' failed
make[1]: *** [ion-qt] Error 1
make[1]: Leaving directory '/home/ubuntu/config.systemd/build-area/ioncoin-2.1.6.1'
dh_auto_build: make -j1 returned exit code 2
debian/rules:18: recipe for target 'binary' failed
make: *** [binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
bzr: ERROR: The build failed.

**Comment by cevap** [comment]
do you maybe miss some files?
`qInitResources_ion_locale()'`

qmake && make breaks too because of missing files (on master). Please check if missing files are the reason.

**Comment by aspaas** [comment]
This problem occurs when e.g. the translations aren't present or cannot be generated. Is there a 0 byte sized file somewhere? Or a warning that an empty file is produced?

**Comment by aspaas** [comment]
Most specifically, are the .qm files generated from the .ts files?

Should look like this: 

~/src/cevap-ion/src/qt/locale$ ls
ion_af_ZA.qm  ion_eo.ts     ion_gl.qm     ion_la.ts     ion_sl_SI.qm
ion_af_ZA.ts  ion_es_CL.qm  ion_gl.ts     ion_lt.qm     ion_sl_SI.ts
ion_ar.qm     ion_es_CL.ts  ion_he.qm     ion_lt.ts     ion_sq.qm
ion_ar.ts     ion_es_DO.qm  ion_he.ts     ion_lv_LV.qm  ion_sq.ts
ion_be_BY.qm  ion_es_DO.ts  ion_hi_IN.qm  ion_lv_LV.ts  ion_sr.qm
ion_be_BY.ts  ion_es_MX.qm  ion_hi_IN.ts  ion_ms_MY.qm  ion_sr.ts
ion_bg.qm     ion_es_MX.ts  ion_hr.qm     ion_ms_MY.ts  ion_sv.qm
ion_bg.ts     ion_es.qm     ion_hr.ts     ion_nb.qm     ion_sv.ts
ion_ca_ES.qm  ion_es.ts     ion_hu.qm     ion_nb.ts     ion_th_TH.qm
ion_ca_ES.ts  ion_es_UY.qm  ion_hu.ts     ion_nl.qm     ion_th_TH.ts
ion_ca.qm     ion_es_UY.ts  ion_id_ID.qm  ion_nl.ts     ion_tr.qm
ion_ca.ts     ion_et.qm     ion_id_ID.ts  ion_pam.qm    ion_tr.ts
ion_cs.qm     ion_et.ts     ion_it.qm     ion_pam.ts    ion_uk.qm
ion_cs.ts     ion_eu_ES.qm  ion_it.ts     ion_pl.qm     ion_uk.ts
ion_cy.qm     ion_eu_ES.ts  ion_ja.qm     ion_pl.ts     ion_ur_PK.qm
ion_cy.ts     ion_fa_IR.qm  ion_ja.ts     ion_pt_BR.qm  ion_ur_PK.ts
ion_da.qm     ion_fa_IR.ts  ion_ka.qm     ion_pt_BR.ts  ion_vi.qm
ion_da.ts     ion_fa.qm     ion_ka.ts     ion_pt_PT.qm  ion_vi.ts
ion_de.qm     ion_fa.ts     ion_kk_KZ.qm  ion_pt_PT.ts  ion_zh_CN.qm
ion_de.ts     ion_fi.qm     ion_kk_KZ.ts  ion_ro_RO.qm  ion_zh_CN.ts
ion_el_GR.qm  ion_fi.ts     ion_ko_KR.qm  ion_ro_RO.ts  ion_zh_TW.qm
ion_el_GR.ts  ion_fr_CA.qm  ion_ko_KR.ts  ion_ru.qm     ion_zh_TW.ts
ion_en.qm     ion_fr_CA.ts  ion_ky.qm     ion_ru.ts
ion_en.ts     ion_fr.qm     ion_ky.ts     ion_sk.qm
ion_eo.qm     ion_fr.ts     ion_la.qm     ion_sk.ts

**Comment by cevap** [comment]
I agree, it looks like translation files, same is on master, just for a note: compile with make instead of qmake still works.

**Comment by ckti** [comment]
Yes, using make a-la ubuntu standard package generation.  Will have a look and see what I can find....in the qt/locale and double-check my compile time libraries.

**Comment by ckti** [comment]
ion_ar.qm is missing in the compilation in qt/locale...

**Comment by ckti** [comment]
qm and ts files are all correct

**Comment by ckti** [comment]
it's not running autoreconf --install; ./configure; make
It's creating its own Makefile using autogen.  This is definitely flags within debian/rules that need to be changed and perhaps an extra step involved.

**Comment by ckti** [comment]
It's running qmake rather than gnu make

**Comment by ckti** [comment]
Ok doing a dput now....have had to do an ./autoreconf;./configure before creating the tar.gz

**Comment by ckti** [comment]
debuild -S -sa then dput gets it up to launchpad.  Just need to tweak the control/rules file a bit more.

**Comment by ckti** [comment]
bzr builddeb works ... finally :) Got a package now just need to check using pbuilder and dput and I think I've finally got it :)

**Comment by ckti** [comment]
:) built on pbuilder now to put it all together :)

**Comment by ckti** [comment]
Should be the last of the changelog/control/rules build and rebuild it's building xenial i386 atm.  Once this is done will create a clean client for both cli and X-Windows under Ubuntu Xenial then install from both source and ppa.  Will probably have to tweak my control file once again to make builds for all systems from a singe source, but this will only have to be done once.

**Comment by ckti** [comment]
yesss :) building for amd64 xenial from exactly the same source as i386 xenial :) Will be putting it up on my ppa once I've installed and tested on a clean xenial system...?tomorrow?  Then will start teasing out the different packages (ioncoin, iond, iond-qt) from this known good source :)

**Comment by ckti** [comment]
Bit of a change of direction, doing a make depends before autoreconf.....xenial amd64 is compiling on a clean system now :)  Probably a few things to change yet but it looks like it's going to work!

**Comment by ckti** [comment]
Just as I thought, gitian 10GB image is too small.  Have created a 20GB and will re-check once done

**Comment by cevap** [comment]
20 will be too small, you need to take 40+

**Comment by mitchellcash** [comment]
Haven't tested with ion, but with Bitcoin I would usually use 40GB images to play it safe and it never caused issues.

**Comment by ckti** [comment]
Have gotten it to build under 20Gb ... with the new git clone it makes a huge difference to storage!  Just crossing fingers on the launchpad depends build....takes a while each time.  slowly but surely :)

**Comment by ckti** [comment]
Right, depends build cannot be done from Launchpad as the files cannot be downloaded from the sources.  Only way to do this is build the binaries and then put the packages up (can do this with what I have now) Will go back to "Regular" ppa builds (will have to figure out the db4.8 includes) and get them up on Launchpad.  I now have a depend build system that works and a ppa build system that works.  Should have the first of the Launchpad ppas up by the end of the week :)

**Comment by ckti** [comment]
Yessss! builds on Launchpad https://launchpad.net/~ckti/+archive/ubuntu/ic.ppa and installs with all dependencies on xenial :)  This package will remain there for now.  I shall start building for the other versions now :)

**Comment by cevap** [comment]
Hehe, :), can we close this now :)?

**Comment by cevap** [comment]
Do you want to maintain it? I think we should move it to ioncoin repository, otherwise we need to change ppa in the documentation. I am open for anything :), thats your baby.

**Comment by ckti** [comment]
Move to the Ioncoin repository definitely!  That's where it belongs.  I have no problem with maintaining it.  It was a load of work to get going.  The secret was to copy DB4.8 from the main source and then everything went smoothly....  I still need to change some details in some of the files in the debian directory (copyright etc).  I would like to re-number the source and builds before it goes live though.  It's ready for alpha and/or beta testing ATM.  If we close this one,do we need to create tickets for each indiv Ubuntu build?  Launchpad should be able to build all versions direct from the master source package....

**Comment by cevap** [comment]
Great, lets consider this repository as non stable/untested, but lets keep it anyway, I think its easier for you to maintenance it here and move add stable packages to ionomy. Stable/tested packages will go to ioncoin repository..

Regarding alpha and beta, we need to define it first, I would say for our project:
 - alpha: first untested public version (experimental)
 - beta: tested during alpha but not every known bug is fixed/feature finished/tested
 - final/release: successfull alpha and beta

with that it could always happen that release has higher version than betas/alphas.

With DB you speak about repositories, or? I assume so, as you are correct, on debian db48 has to be somehow as dependency there. 

Regarding copyright, I think we agree, everything released on cevap has CEVAP copyright lines and is always under MIT license (for now).

We need to adapt more public information, as well as donation addresses. There are projects for that, we need to create more tasks/cards to finish it. Please refer to this issue here.

I will suggest to close this one for now, you can reopen any time or create new, more specific describing issue/goal.

PS: to reopen, simply leave reply/click open ticket, you should be able, please contact me if it does not work, you can reopen it just to test if you want.

**Comment by ckti** [comment]
New packages up at https://launchpad.net/~ckti/+archive/ubuntu/incoin-test/+packages (yes I'm aware of the spelling error incoin not ioncoin)  Will clean up some of the build (2 man pages for binaries that are not installed) and create an ioncoin-master ppa with 3 packages for each build; ioncoin, ioncoin-qt and iond.

**Comment by ckti** [comment]
Reverse building from Launchpad to pbuilder --- seemed a good time to double-check that everything is correct in the builds so far (launchpad works, but making sure local builds work as well -- depends build to be done from pbuilder images as well).  Two man pages to remove and separate iond ion-qt and ioncoin to create.  Will be back in a fortnight now -- mon 14th aug will restart in earnest

**Comment by ckti** [comment]
Have put up UNTESTED debs from latest cevap source in incoin-test built and installed correctly.  will build on headless clones either later today or tomorrow

**Comment by ckti** [comment]
all build in on amd64 and i386 correctly under pbuilder and launchpad.  trusty, xenial and zesty.

**Comment by Bige086** [comment]
I would love to test this :) Nice work ckti

**Comment by ckti** [comment]
currently setting up a system to update on a 24 hr basis the packages (with commit versions) on launchpad.

**Comment by ckti** [comment]
Will be putting up as commit version changes....have most of the process finalized

**Comment by ckti** [comment]
Have version 675ae7b up under [https://launchpad.net/~ckti/+archive/ubuntu/ic.depends/+packages](https://launchpad.net/~ckti/+archive/ubuntu/ic.depends/+packages)  incoin-test will be deleted by the end of this week

**Comment by ckti** [comment]
ioncoin, iond and ion-qt packages going up to launchpad now under new PPA ioncoin-small https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-small .  Some compilation issues under zesty, checking whether the occur under Launchpad as well

**Comment by ckti** [comment]
ioncoin, iond and ion-qt packages going up to launchpad now under new PPA ioncoin-small https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-small .  Some compilation issues under zesty, checking whether the occur under Launchpad as well

**Comment by ckti** [comment]
Still a bit of bother with the iond, ioncoin and ion-qt building.  Think I've found the solution though...

**Comment by ckti** [comment]
Solution works, testing compile and run on pbuilder then uploading to ioncoin-small

**Comment by ckti** [comment]
xenial and trusty iond packages up at https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-small (still test state, will be adding /etc/default/iond file and /lib/systemd/system/iond.service files in the last test iteration).

**Comment by ckti** [comment]
all packages up at https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-small (still test state, will be adding /etc/default/iond file and /lib/systemd/system/iond.service files in the last test iteration).

**Comment by ckti** [comment]
Latest test iteration up on https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-small packages have the correct binaries for each package.  Just iond.service and /etc/default/iond for iond and ioncoin and the /usr/share/pixmap image for all three

**Comment by ckti** [comment]
upping to ver 3 due to error in package scripts :(

**Comment by ckti** [comment]
upping to ver 3 due to error in package scripts :(
removing the old ones is a case of doing "_sudo dpkg -r --force-all ion<-qt | d | coin>_"

**Comment by ckti** [comment]
ion-qt for zesty is now up under version 3
test for ion-qt running has been added properly and tested both ways under x86_64 zesty

**Comment by ckti** [comment]
version 3 needs to be rebuilt again, still a problem with pre/post rm scriptlets.

**Comment by ckti** [comment]
think the pre/post scripts are right just doing a zesty install and then will build and test functionalty under gitian

**Comment by ckti** [comment]
finally starting a full gitian compile on the version  2.1.6.2 bb68b3b got the script's bugs out afaict....

**Comment by ckti** [comment]
currently uploading to https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-small version bb68b3b all 3 distros and 3 packages per distro.  The startup/shutdown scripts aren't 100% yet.  Still need to  download from ppa and double-check all install properly.

**Comment by ckti** [comment]
have upped the revision to 2...will be uploading later today

**Comment by ckti** [comment]
now compiling all 9 packages locally with pbulder...all looks OK so far

**Comment by ckti** [comment]
looks like tomorrow on revision 2 still compiling first run and tests will take a few hours

**Comment by ckti** [comment]
first run compilation good, all pre and post install scripts running without issues.  /lib/systemd/iond.service file and /etc/default file are being created.  creaating .deb packages for all 9 locally. Will test today with the aim of having the revision 2 files in place today.

**Comment by ckti** [comment]
still some sorting out to do with start/stop scripts under trusty. upstart will have some errors in version 2.

**Comment by ckti** [comment]
the packages install nicely from launchpad ppa:ckti/ioncoin-small, trusty needs a re-jig to upstart/systemV and there is a juxtaposed character in the .service script for iond :P

**Comment by ckti** [comment]
Got zesty and xenial compiling ok, make install error on trusty.  Have to go though it.  ver 3 for xenial and zesty will be up this evening.

**Comment by ckti** [comment]
Seems like it's just iond under trusty ion-qt and ioncoin compile without issue.  doesn't like the name iond being used in one of the debian scripts.

**Comment by ckti** [comment]
Seems like it's just iond under trusty ion-qt and ioncoin compile without issue.  doesn't like the name iond being used in one of the debian scripts.

**Comment by ckti** [comment]
All up at launchpad https://launchpad.net/%7Eckti/+archive/ubuntu/ioncoin-small.  Still have to install them on vms and double check them but this should be the last test version before putting them in ioncoin-master.

**Comment by ckti** [comment]
Looks like another revision (#4) in test.  /etc/default/iond not creating and /usr/share/pixmaps not going up in ioncoin.

**Comment by ckti** [comment]
version 4 going up atm.  All looks good. Will test against VB images.

**Comment by ckti** [comment]
ioncoin package to rebuild under trusty i386... rc.d script not there and user in /etc/default/iond is populated (my end ... must have missed something in the build scripts)

**Comment by ckti** [comment]
Have ion-qt up for all 3 Ubuntu variants 32 and 64 bit.  iond is up for xenial and zesty 32 and 64 bit.
urf is https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-master will fix up ioncoin and the one iond package tomorrow

**Comment by ckti** [comment]
new version, new compile, new test....

**Comment by ckti** [comment]
ioncoin-master is empty until new builds installed, ioncoin-small is no l;onger extant and a new ioncoin-test repository http:///launcpad.net/~ckti/ioncoin-test  is now in place

**Comment by ckti** [comment]
ioncoin-small is now deleted, ioncoin-master is empty until the verion is in place and there is a new repository ioncoin-test https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-test

**Comment by ckti** [comment]
Getting everything compiling once again now.

**Comment by ckti** [comment]
Uploading to https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-test Still chasing a bug in ioncoin.  iond and ion-qt get installed but the systemd startup scripts and /etc/default/ion don't get installed. I'm sure it's going to be something very simple on my end.  No problems installing and running ioncoin by hand.

**Comment by cevap** [comment]
good that you mention it, because looking now, I would like to ensure that also other gui's work, like ie. cinnamon, which currently is not the case.

Does problem with scripts apply to every version or to some specific?

**Comment by cevap** [comment]
and it would be probably usefull if we can add bootstrap to the repo too, but lets do it after everything else which we aimed is finished. Great work, thanks :+1:

**Comment by cevap** [comment]
can we take label "bug" out?

**Comment by aspaas** [comment]
@cevap : maybe we can add the bootstrap file to an other repo, so we can keep the size of this repo small?

**Comment by ckti** [comment]
Was going to keep the master copy in my launchp[ad and then have a copy on cevap Launchpad.  All toat (atm) it's 407.1 Mb on Launchpad (incl db 4.8) under commit f3a3ef4.  Ion-cli works a treat btw :) had to update my start/stop scripts :) nicely done (:

**Comment by cevap** [comment]
I tested packages, they all work, some overview:

- [X] Installation
     - [X] Install on debian based os
     - [X] Install on opensuse/fedora based os
     - [X] Install on windows based os
- [ ] Shortcuts for gnome are there, but not on ie. cinnamon, did not check KDE and other on that point
     - [X]  Shortcuts on Windows for the main
     - [ ]  Shortcuts on Windows for the testnet
     - [ ] Shortcuts on all systems for ion-cli and ion-tx, including testnet
- [ ] Config file is installed but we did not preconfigure it. We need to discuss, I would probably force to add `maxconnections=3`or even `maxconnections=2` , as thats what would solve sync problems for most users who reported about it, lets call it a workaround or dirty solution for existing problem.
- [ ] Useful scripts
     - [ ] Backup all my private keys to unencrypted/signed/signed+encrypted (wallet.dat/XML/HTML/...)
     - [ ] Backup blockchain data (full backup unencrypted/signed/signed+encrypted)
     - [ ] Description, documentation, faq as well as release infos for installers (per default disabled but user can mark for installation)
     - [ ] Update everything including documentation to the latest release (can be used as autoupdate, but it is not recommended currently)
     - [ ] Artworks installer (ie. Windows theme, wallpapers, boot loader backgrounds, ...)

**Comment by ckti** [comment]
? confused ? built for the 3 supported Ubuntu OSes...trusty xenial & zesty.  hadn't widened my net to anything else,  I can do if need be.  Will have to set up an autobuild on a nightly basis.

**Comment by cevap** [comment]
yes, I know, just saying. If you test it on same systems but with other gui (ie: cinnamon is available for install) you will see that there are no shortcuts in the startmenu even.

**Comment by ckti** [comment]
ok, just realized what you were saying. Will have a look at  intallling in various Ubuntu guis....this might take me a while though.  It's a matter of adjusting the postinst and prerm scripts to put shortcuts in and take shortcuts out.  I will give this a go over the course of next week.....

**Comment by ckti** [comment]
ok, just realized what you were saying. Will have a look at  intallling in various Ubuntu guis....this might take me a while though.  It's a matter of adjusting the postinst and prerm scripts to put shortcuts in and take shortcuts out.  I will give this a go over the course of next week.....

**Comment by ckti** [comment]
First set of master packages (git revision ec7d246) up at https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-master ... install and run no problem.  Will start looking at setting up icons &c in the various Window Managers and adding more verbose functionality to the installation/removal of these packages.

**Comment by ckti** [comment]
Bleeding edge up at  https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-2.1.6.3  Will automate this system for a nightly build.

**Comment by ckti** [comment]
It will bit a bit more complex than anyone thought to do the start menu bits.  We first have to ascertain who the daemon/qt is running as in /etc/default/iond.  At the moment this is only populated with $USER="" which is read by the init scripts/service. The user is left to edit this file and populate it with either their own details or to add a user to the system.  The qt daemon automatically chooses the calling user in the ion-qt package.  The ioncoin package has both iond and ion-qt.

  This can be accomplished just will take a bit more thinking.  Pre-populating  .ioncoin.conf again depends on which user id the daemon is running with.  As it stands, I can forsee 3/4 weeks worth of effort going into this.  I will have to do a (gasp) flowchart/algorithm to see what needs to be done a bit more clearly.

**Comment by ckti** [comment]
newest build up at https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-master version 7ddca9a

**Comment by ckti** [comment]
Now automated.  All new packages will go to https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-master on a nightly basis.

**Comment by ckti** [comment]
Having had a little while to think about the installation of the Ubuntu packages the best way forward will be to use the installing user's UID,  The pre-configuring of ~/.ioncoin/ioncoin.conf, /etc/default/iond and menu items can be done using the postinst script.  If a user wants to change this they can do so after installation is complete.  This is not a trivial thing to do as all window managers will have to be taken into account in some sort of ?case? statement in postinst.

 Will start with getting the user configured in /etc/default/iond.

**Comment by ckti** [comment]
working on getting application menu items installed with postinst and removed with postrm

**Comment by ckti** [comment]
have now got the method for installing application menu items

**Comment by ckti** [comment]
now testing on all 6 platforms.

**Comment by ckti** [comment]
working under all 6 platforms.  all three packages tested against stock Ubuntu desktop.  Zesty amd64 has been tested with all major spins as well: kubuntu, lubuntu, budgie, gnome, mate, and xubuntu.  Will test the rest against these in the next little while.  These packages are ready to install from  ppa:ckti/ioncoin-master

**Comment by ckti** [comment]
couple of small tweaks needed for iond.service ... currently building

**Comment by ckti** [comment]
Final packages commit version 5bc80c4 revision 12 up at ppa:ckti/ioncoin-master (https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-master).  Will be building artful (17.10) to add into the mix.

**Comment by ckti** [comment]
artful commit version 5bc80c4 revision 12 iond & ion-qt reviosion 13 ioncoin up at ppa:ckti/ioncoin-master (https://launchpad.net/~ckti/+archive/ubuntu/ioncoin-master).
