### ISSUE TITLE
Testing v3.1.0-rc6

### ISSUE THREAD

**Issue by cevap** [cevap/ion#73]
Please test https://github.com/cevap/ion/releases/tag/v3.1.0-rc6 and report here if for you everything runs well. If there is some issue, please create a new issue.

If you want to help by [translating](https://www.transifex.com/cevap/ioncoin/), please [join and help translate ion](https://www.transifex.com/signup/?join_project=ioncoin).

# Testing v3.1.x

- [Testing v3.1.x](#testing-v31x)
  - [Tests on main net](#tests-on-main-net)
    - [Tested staking, masternode and multisend](#tested-staking-masternode-and-multisend)
  - [Gitian builds tests on main](#gitian-builds-tests-on-main)
    - [Test Ion QT](#test-ion-qt)
    - [RPC tests](#rpc-tests)
  - [SNAP builds compatibility](https://build.snapcraft.io/user/cevap/ion)
    - [x] amd64
    - [x] i386
    - [x] armhf
    - [x] arm64 (_supported since_ https://github.com/cevap/ion/commit/65de552b95241e406960a739611790746f51d907)
    - [x] ppc64el (_supported since_ https://github.com/cevap/ion/commit/65de552b95241e406960a739611790746f51d907)
    - [x] s390x ~currenlty not supported, but we work on that (: `configure: error: "Big Endian not supported"`), [here is the build log](https://build.snapcraft.io/user/cevap/ion/403420) with the error.~
           Supported since: https://github.com/cevap/ion/commit/65de552b95241e406960a739611790746f51d907
### Tested staking, masternode and multisend

***Maintenance Mode*** will start at GMT: _Sunday, 6. January 2019 00:00:02_ (epoch time: 1546732802)

***Use the new spork key*** [after Thursday, GMT: Monday, 31. December 2018 00:00:01](https://github.com/cevap/ion/blob/e9f7dc6f38b9e7c47b9f8137cf302a71ad4d14e3/src/chainparams.cpp#L174-L175)
***Reject old spork key*** [after Wednesday, GMT: Sunday, 6. January 2019 00:00:01](https://github.com/cevap/ion/blob/e9f7dc6f38b9e7c47b9f8137cf302a71ad4d14e3/src/chainparams.cpp#L174-L175)

If you want to check it in your wallet, run `ion-cli spork show` and check _SPORK_9_ZEROCOIN_MAINTENANCE_MODE_ for changes. 

- [x] Create, start and launch masternode 
- [x] Masternode stake
- [x] Multisend
        _[testmultisend1 txid](https://chainz.cryptoid.info/ion/tx.dws?e41e1032b1bac02cc29c6e8838409a5cb27bbfc7ef032dc98f2e23a3bcdff2cf.htm) and [testmultisend2 txid](https://chainz.cryptoid.info/ion/tx.dws?13a9b8b609e846d616a2ebad50d00b1b83071b2a85f2c0f9581e8073a3e2b41c.htm)_
- [ ] ~Voting~ (_can be tested [after the old spork key becomes inactive](https://github.com/cevap/ion/blob/e9f7dc6f38b9e7c47b9f8137cf302a71ad4d14e3/src/chainparams.cpp#L174-L175)_)
- [x] Created tx of Zerocoin V1 with wallet v3.1.x should rejected by the network
- [ ] ~Spend Zerocoin V1~ (_can be tested after [block that zerocoin v2 becomes active - roughly Tuesday, January 8, 2019 10:24:00 AM GMT](https://github.com/cevap/ion/blob/e9f7dc6f38b9e7c47b9f8137cf302a71ad4d14e3/src/chainparams.cpp#L174-L175) is reached becomes inactive_)
- [ ] ~Create Zerocoin V2~ (_can be tested after [block that zerocoin v2 becomes active - roughly Tuesday, January 8, 2019 10:24:00 AM GMT](https://github.com/cevap/ion/blob/e9f7dc6f38b9e7c47b9f8137cf302a71ad4d14e3/src/chainparams.cpp#L174-L175) is reached becomes inactive_)

## Gitian builds tests on main

Gitian builds built on bionic can be downloaded [here](https://github.com/cevap/ion/releases/tag/v3.1.0-rc6).

### Test Ion QT

- [x] runs on all operating systems (_partially, there are some bugs which have to be resolved, but they run_)
  - [x] Test run on Windows 32 and 64 bit version (works, no issues)
    - [x] Windows 10 64-Bit (en)
  - [x] Test run on Linux (_works, there is [one issue](#76) with users OS which is to be considered as bug, but here you can read more about it as well as a workaround which resolves the issue_)
    - [x] Ubuntu desktop 18.04 LTS (bionic)
    - [x] Debian Stretch with gnome
    - [x] Fedora 28
    - [x] Fedora 27
  - [x] Test run on RaspberryPi
    - [x] Raspbian 
    - [x] Ubuntu Core
  - [ ] macOS
    - [x] macOS Mojave (macOS v10.14.1) (__there are [issues](#issuecomment-445896246 )__)
    - [x] macOS High Sierra (macOS 10.13.4, macOS v10.13.5 and macOS v10.13.6) (***there are issues***)
    ![thanks @pcminer](https://user-images.githubusercontent.com/24996551/49766076-74582480-fcd4-11e8-8c60-603539090554.png)
    - [x] macOS Sierra (macOS v10.12.0, macOS v10.12.4, macOS v10.12.6)
    - [x] OS X El Capitan (OS X v10.11.0 and OS X v10.11.6)
    - [x] OS X Yosemite (OS X v10.10.0 and OS X v10.10.5)
    - [x] OS X Mavericks (OS X v10.9.0 and OS X v10.9.5)
    - [x] OS X Mountain Lion (OS X v10.8.0 and OS X v10.8.5 with Security Update 2015-001)
    - [ ] Mac OS X Lion (Mac OS X v10.7.0)
    - [ ] Mac OS X Snow Leopard (Mac OS X v10.6.0 )
    - [ ] Mac OS X Leopard (Mac OS X v10.5.0 & Mac OS X v.10.5.8)

**Comment by jpass022** [comment]
Tested MAC QT version on macOS Mojave Version 10.14.1. Crashed first two times tried to start, QT started on third attempt. Enabled uPNP in Preferences to get connections.

**Comment by cevap** [comment]
for linux builds built on bionic with docker keyboard is missing in qt and this is the error which occures:
```
xkbcommon: ERROR: failed to add default include path auto
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
```

One workaround for testers would be to set this var when launching qt for a test:
```bash
export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb && ./ion-qt
```

If you will launch the wallet many times, place this line into your profile definition:
```bash
export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb >> /home/gitianuser/.profile
```

**Comment by ckti** [comment]
WIll test on trusty -> bionic i386/amd64 all distros and Fedora 27/28 all distros.  will also get depends/launchpad made up with the QT_XKB_CONFIG added to the global profile with postinst/prerm scripts.

**Comment by cevap** [comment]
dont bother with XKB, we have a patch for 5.9.x, it is a little bit different than in 5.7 and I do guess we should not bother with patching XKB for 5.7 as we want to move anyway to higher versions.

**Comment by ckti** [comment]
that's all of trusty & xenail done i386 & x86_64 all distros

**Comment by ckti** [comment]
aarch64 raspian "no such file or directory" will try armbian

**Comment by ckti** [comment]
armbian works

**Comment by ckti** [comment]
armhf raspian works

**Comment by ckti** [comment]
fedora arm not 100% static, had to install libX11-xcb-1.6.5-4.fc27

**Comment by ckti** [comment]
Hmm, interesting
ldd ./ion-3.1.00/bin/ion-qt 
	linux-vdso.so.1 (0xbeef1000)
	libX11-xcb.so.1 => /lib/libX11-xcb.so.1 (0xb57b1000)
	libX11.so.6 => not found
	libxcb.so.1 => not found
	**libfontconfig.so.1 => not found**
	l**ibfreetype.so.6 => not found**
	libpthread.so.0 => /lib/libpthread.so.0 (0xb5788000)
	libdl.so.2 => /lib/libdl.so.2 (0xb5775000)
	libanl.so.1 => /lib/libanl.so.1 (0xb5761000)
	librt.so.1 => /lib/librt.so.1 (0xb574a000)
	libm.so.6 => /lib/libm.so.6 (0xb56c3000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb5696000)
	libc.so.6 => /lib/libc.so.6 (0xb554b000)
	/lib/ld-linux-armhf.so.3 (0xb6f5c000)

**Comment by ckti** [comment]
That's all of armhf xenial, raspbian, fedora 27 and fedora 28

**Comment by ckti** [comment]
That's all of aarch64 xenial, bionic, fedora 27 and fedora 28

**Comment by ckti** [comment]
That finishes all of the tests with bionic i386, amd64 and all distros

**Comment by cevap** [comment]
next is testing rc7.2 which includes
