### ISSUE TITLE
Qt: Failed to create XKB context!, keyboard is missing in qt and this is the error which occures:

### ISSUE THREAD

**Issue by cevap** [cevap/ion#76]
```
xkbcommon: ERROR: failed to add default include path auto
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
```

One workaround for testers would be to set this var when launching qt for a test:
```bash
export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb && ./ion-qt
```

If you will launch the wallet many times, place this line into your profile definition:
```bash
export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb >> /home/gitianuser/.profile
```

_Originally posted by @cevap in https://github.com/cevap/ion/issue_comments#issuecomment-445954818_

**Comment by ckti** [comment]
I can confirm that this bug disappears when using qt 5.9.1

**Comment by ckti** [comment]
found that QT_XKB_CONFIG_ROOT can be any value as long as it's set

**Comment by cevap** [comment]
resolved by compiling on trusty, XKB fix is only required when we switch 100% to 5.9.x or higher. XKB fix works on rc7 and rc8.

**Comment by cevap** [comment]
missing qt fontbase etc errors were caused if pkg fails (as patch was not good), if patch is correct, then everything is fine.

**Comment by cevap** [comment]
I will close this as it is resolved for now, I will reopen this issue after we pull update_dependencies branch.
