### ISSUE TITLE
When building in Ubunt 16.04 it fails from Guide

### ISSUE THREAD

**Issue by Bige086** [cevap/ion#78]
VMWare
6 core
8gb ram
I am running Ubuntu 16.04 and followed the linux build for QT and this is the error I recieve:
build/ion.o: In function `main':
ion.cpp:(.text.startup+0x148): undefined reference to `qInitResources_ion_locale()'
collect2: error: ld returned 1 exit status
Makefile:680: recipe for target 'ion-qt' failed
make: *** [ion-qt] Error 1

**Comment by aspaas** [comment]
This error means that some resource file wasn't build correctly, probably a translation file. 

Please provide:
1) A link to the guide you used
2) The exact build commands you entered, from the beginning
3) The output of build.log when  you replace the last build command with `make 2>&1 | tee -a build.log`

**Comment by Bige086** [comment]
1. https://github.com/cevap/ion/blob/master/doc/build-unix.md
2. Sudo apt-get update
sudo apt-get upgrade
sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils
sudo apt-get install libboost-all-dev
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:ionomy/ioncoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev
sudo apt-get install libminiupnpc-dev
sudo apt-get install libzmq3-dev
sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
sudo apt-get install libqrencode-dev
git clone https://github.com/cevap/ion
cd ion
sudo qmake
sudo make

**Comment by aspaas** [comment]
OK I see.
So we didn't update the qmake build files. Honestly, keeping them up to date sounds like double work to me. @cevap: what do you think, are there advantages of keeping the qmake files up to date, or should we ditch them? I'd prefer sticking to the autotools version.

@Bige086: please try build method 1 from that manual. That should work.
```
./autogen.sh
./configure
make
```

**Comment by Bige086** [comment]
autotools look great, Ill give those a shot.  No need to double the work!

**Comment by aspaas** [comment]
Conclusion: when cleaning up the repo, files that are build by autotools but are not build by qmake were removed from the github repo. We could update the qmake files to build them too, but since the qmake routine no longer offers advantages, we'll remove qmake support to avoid double work (Issue #79).

Thank you for reporting this!

I'm closing the issue; please reopen it if it doesn't work.
