### ISSUE TITLE
Error When Building Windows HOST=x86_64-w64-mingw32

### ISSUE THREAD

**Issue by Bige086** [cevap/ion#85]
#### If so, please list the steps to reproduce below:
1. While following the windows build guide using bash in windows 10 running everything goes smoothly until it try to make: make HOST=x86_64-w64-mingw32 the make fails, also happens on ubuntu builds
2. Error:
Building native_nsis...
/bin/sh: 1: scons: not found
funcs.mk:242: recipe for target '/home/bige/ion/depends/work/build/x86_64-w64-mingw32/native_nsis/3.01-e4d86e28d2b/./.stamp_built' failed
make: *** [/home/bige/ion/depends/work/build/x86_64-w64-mingw32/native_nsis/3.01-e4d86e28d2b/./.stamp_built] Error 127

### Expected behaviour
Should continue to make the file

### Actual behaviour
Error:
Building native_nsis...
/bin/sh: 1: scons: not found
funcs.mk:242: recipe for target '/home/bige/ion/depends/work/build/x86_64-w64-mingw32/native_nsis/3.01-e4d86e28d2b/./.stamp_built' failed
make: *** [/home/bige/ion/depends/work/build/x86_64-w64-mingw32/native_nsis/3.01-e4d86e28d2b/./.stamp_built] Error 127

### Screenshots.
![error](https://user-images.githubusercontent.com/11136947/29341258-fd94a0da-81d7-11e7-9e9b-dcd3fe920c08.png)

### Machine specs:
- OS: Window 10 Ubuntu bash
- CPU: FX 8370
- RAM: 16GB
- Disk size: 512Gb
- Disk Type (HD/SDD): SSD

**Comment by aspaas** [comment]
Excellent, thanks!
NSIS is the installer creator , which creates Windows installers. 
We added it to the depends system because the default version provided by eg Ubuntu doesn't include shipper support for Unicode characters.
Compiling NSIS requires scons, but that's not installed by default.
scons should be added to the build instructions in [doc/build-windows.md](doc/build-windows.md)

**Comment by aspaas** [comment]
@jpass022: I think you were also looking at the flow of the build documents? If so, could you please check that the documents you were looking at also include 'scons' as a dependency for cross-compiling the Windows version?
Thanks!
@Bige086: it should work now. Thanks again for noticing. (Please double check the install destination folder exists before you try to install, the folder is not automatically created).
I'm closing the issue.
