### ISSUE TITLE
New SSL Version not working

### ISSUE THREAD

**Issue by ypal2** [cevap/ion#88]
This issue tracker is only for technical issues related to ion-core.

General ion questions and/or support requests and are best directed to the [IonTalk Forums](https://www.iontalk.net) or [Slack](https://ionomy.slack.com).

For reporting security issues, please email [support@ionomy.com](mailto:support@ionomy.com).

### Describe the issue
crypter.cpp: In member function ‘bool CCrypter::Encrypt(const CKeyingMaterial&, std::vector<unsigned char>&)’:
crypter.cpp:69:20: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined
     EVP_CIPHER_CTX ctx;
                    ^~~
crypter.cpp: In member function ‘bool CCrypter::Decrypt(const std::vector<unsigned char>&, CKeyingMaterial&)’:
crypter.cpp:96:20: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined
     EVP_CIPHER_CTX ctx;
                    ^~~
crypter.cpp: In function ‘bool EncryptAES256(const SecureString&, const SecureString&, const string&, std::__cxx11::string&)’:
crypter.cpp:152:20: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined
     EVP_CIPHER_CTX ctx;
                    ^~~
crypter.cpp: In function ‘bool DecryptAES256(const SecureString&, const string&, const string&, SecureString&)’:
crypter.cpp:182:20: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined
     EVP_CIPHER_CTX ctx;
                    ^~~
crypter.cpp: In member function ‘bool SecMsgCrypter::Encrypt(uint8_t*, uint32_t, std::vector<unsigned char>&)’:
crypter.cpp:382:20: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined
     EVP_CIPHER_CTX ctx;
                    ^~~
crypter.cpp: In member function ‘bool SecMsgCrypter::Decrypt(uint8_t*, uint32_t, std::vector<unsigned char>&)’:
crypter.cpp:410:20: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined
     EVP_CIPHER_CTX ctx;
                    ^~~
Makefile:3417: recipe for target 'libion_server_a-crypter.o' failed
make[2]: *** [libion_server_a-crypter.o] Error 1
make[2]: Leaving directory '/home/pi/Desktop/ion/ion/src'
Makefile:5710: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/Desktop/ion/ion/src'
Makefile:736: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:
Wallet installation steps
After step make i got this error with SSL
SSL Version : OpenSSL 1.1.0f  25 May 2017
### Expected behaviour
To finish wallet compilation

### Actual behaviour
Stop at make command 

### What version of ion-core are you using?
2.1.6

### Machine specs:
Raspberry Pi 3

**Comment by aspaas** [comment]
Not confirmed yet, but appears to be a legit issue.
See:
- https://github.com/bitcoin/bitcoin/pull/9326
- https://github.com/bitcoin/bitcoin/pull/9326/commits

Will be addressed when incorporating bitcoin related improvements.
Thank you so much for reporting this!
For now, a workaround is to follow the cross compilation steps using the depends folder when compiling for systems with OpenSSL 1.1 (and above). See for example here: [ARM Cross-compilation](https://github.com/cevap/ion/blob/master/doc/build-unix.md#arm-cross-compilation)

**Comment by cevap** [comment]
It is not an issue but a dependency.

Openssl higher than 1.0.2 breaks as one function was dropped with version 1.1..0 which is required by the core. If you google you will find out more about it. 

We will do the same what bitcoin will do and until 1.0.2's EOL is plenty of time. It can be an issue for network related stuff but there are no known security issues.

Closed with that.
